### ISSUE TITLE
Divi Theme Visual Builder And Visual Composer Conflict

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#57]
When GiveWhen plugin is active, and I edit or create a page using Divi Builder, when publishing/updating the page it reverts back to the basic page editor with the ElegantThemes shortcodes displayed instead of remaining inside the Divi Builder.

When I deactivate our plugin and then try again everything works as expected, so the bug seems to be on our side.

**Comment by tejasm-itpath** [comment]
@angelleye 
I have tested it again , There is some problem with Divi theme (in this version). 
In older version of Divi , It works perfect 
And sometimes in this version also it works perfect But sometimes not. 
Also I have tried deactivating our plugin and then created page but it still loads shortcodes and default editor instead of the Divi builder.

**Comment by angelleye** [comment]
So what is the commit you made here after your comment?  Is that supposed to fix the problem?

Can you point out where the issue is with Divi so I can bring it to their attention?

**Comment by tejasm-itpath** [comment]
@angelleye  This is the bug from our plugin. right now I am working on that. It also does same with Visual builder plugin too.
