### ISSUE TITLE
Cancel Billing agreement button in the Givers list

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/GiveWhen#60]
Right now Billing agreement is being canceled when user/giver is being deleted.
We required a button on the Givers List (admin side) from where site owner can remove the billing agreement for particular giver

**Comment by tejasm-itpath** [comment]
@angelleye 
After Cancelling Billing agreement , we are still showing that giver in the givers list of the Goal , 
Do we need to show there or we required to remove all the details of that user related to GiveWhen.
And what if the user has signed up for more than one goal ? 
Do we need all details to be removed of that particular user on every goal ?

**Comment by angelleye** [comment]
The Giver list is unique to each goal, right?  So if somebody is signed up for multiple goals, and I cancel their agreement for a single goal, it should only cancel for that one goal.  We can improve upon that later, but for now that will be fine.

I don't want to remove them from the Giver list when canceled because the site owner may still want to review transaction history even if the user has canceled.   So we can leave them in the list, but we could highlight the row or add a little icon or do something to show that the Giver is no longer active on that goal.
